package org.blockzter.haha.dal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.blockzter.haha.dal.model.FloorRoom;
import org.blockzter.haha.dal.model.Room;

/**
 * Class _Floor was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Floor extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String FLOOR_ID_PK_COLUMN = "floor_id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<FloorRoom> FLOOR_ROOMS = Property.create("floor_rooms", FloorRoom.class);
    public static final Property<List<Room>> ROOMS = Property.create("rooms", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setFloor_rooms(FloorRoom floor_rooms) {
        setToOneTarget("floor_rooms", floor_rooms, true);
    }

    public FloorRoom getFloor_rooms() {
        return (FloorRoom)readProperty("floor_rooms");
    }


    @SuppressWarnings("unchecked")
    public List<Room> getRooms() {
        return (List<Room>)readProperty("rooms");
    }


}
