package org.blockzter.haha.dal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.blockzter.haha.dal.model.Floor;
import org.blockzter.haha.dal.model.Room;

/**
 * Class _FloorRoom was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FloorRoom extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String FLOOR_ID_PK_COLUMN = "floor_id";
    public static final String ROOM_ID_PK_COLUMN = "room_id";

    public static final Property<List<Floor>> FLOORS = Property.create("floors", List.class);
    public static final Property<List<Room>> ROOM = Property.create("room", List.class);

    public void addToFloors(Floor obj) {
        addToManyTarget("floors", obj, true);
    }
    public void removeFromFloors(Floor obj) {
        removeToManyTarget("floors", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Floor> getFloors() {
        return (List<Floor>)readProperty("floors");
    }


    public void addToRoom(Room obj) {
        addToManyTarget("room", obj, true);
    }
    public void removeFromRoom(Room obj) {
        removeToManyTarget("room", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Room> getRoom() {
        return (List<Room>)readProperty("room");
    }


}
