package org.blockzter.haha.dal.model.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;
import org.blockzter.haha.dal.model.Device;
import org.blockzter.haha.dal.model.Room;

/**
 * Class _RoomDevice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RoomDevice extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String DEVICE_ID_PK_COLUMN = "device_id";
    public static final String ROOM_ID_PK_COLUMN = "room_id";

    public static final Property<List<Device>> RM_DEVICE_DEVICE = Property.create("rm_device_device", List.class);
    public static final Property<List<Room>> RM_DEVICE_RM = Property.create("rm_device_rm", List.class);

    public void addToRm_device_device(Device obj) {
        addToManyTarget("rm_device_device", obj, true);
    }
    public void removeFromRm_device_device(Device obj) {
        removeToManyTarget("rm_device_device", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Device> getRm_device_device() {
        return (List<Device>)readProperty("rm_device_device");
    }


    public void addToRm_device_rm(Room obj) {
        addToManyTarget("rm_device_rm", obj, true);
    }
    public void removeFromRm_device_rm(Room obj) {
        removeToManyTarget("rm_device_rm", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Room> getRm_device_rm() {
        return (List<Room>)readProperty("rm_device_rm");
    }


}
